eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}  # Local-specific Eureka URL
      fetch-registry: true
      register-with-eureka: true
  instance:
    hostname: ${spring.application.name}
    prefer-ip-address: true
    healthCheckUrlPath: /actuator/health
    statusPageUrlPath: /actuator/info
    healthCheckUrl: http://${eureka.instance.hostname}:${eureka.instance.non-secure-port}${eureka.instance.healthCheckUrlPath}
    statusPageUrl: http://${eureka.instance.hostname}:${eureka.instance.non-secure-port}${eureka.instance.statusPageUrlPath}

spring:
  rabbitmq:
    host: localhost

restaurant:
  service:
    url: http://localhost:${restaurant.service.port}